# Generated by Django 5.2.14 on 2026-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='commenti_foto/'),
        ),
        migrations.AddField(
            model_name='post',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='post_foto/'),
        ),
    ]
